apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-app
spec:
  type: NodePort
  ports:
    - name: http 
      nodePort: 31013   
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx-app

---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: app-data
spec:
 storageClassName: hostpath
 capacity:
  storage: 4Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/data/app-data"
  type: Directory

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-claim
  labels:
    app: nginx-data
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-deploy
  labels:
    app: nginx-app
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: app-data-claim
      containers: 
      - name: nginx-app
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: app-data
            mountPath: /usr/share/nginx/html/
